const {catchAsync, catchWithCustomError} = require('./catchAsync');

console.log('delete me');

module.exports = { catchAsync ,catchWithCustomError };